### ISSUE TITLE
Doesn't take pictures after focusing

### ISSUE THREAD

**Issue by vanderLo** [obs1dium/FocusBracket#1]
SONY ALPHA 6000, FW 3.10, Sony ZEISS Lens with AF
-Auto review was disabled
-Camera was in manual focus mode

Bug: The camera doesn't take pictures after focusing: Focus -> Pause -> Focus -> Pause etc.

Bug: Sometimes, after leaving the app with the respective button (Menu button would be more intuitive though, because the other Sony Camera Apps use this as well) and then restarting the app, it keeps asking for the maximum focus point (right from the beginning) instead of the minimum focus point. It probably doesn't close the last instance, but reopens it..

General note: Usability of the app is so far pretty good!

**Comment by obs1dium** [comment]
> The camera doesn't take pictures after focusing

Weird. Unfortunately I can only test with the gear I have at my disposal.

> it keeps asking for the maximum focus point

I noticed that as well.

**Comment by vanderLo** [comment]
I have the Sony Bracket Pro App (https://www.playmemoriescameraapps.com/portal/usbdetail.php?eid=IS9104-NPIA09014_00-000001), which works though. So I guess this isn't a Camera/Lens related issue.

**Comment by obs1dium** [comment]
Yeah, I would expect the Sony apps to work properly... 
Maybe you could try [this bracketing app](http://psafs.pixub.com/) and see if it also works for you.

**Comment by vanderLo** [comment]
The app (v1.5) works fine.

**Comment by vanderLo** [comment]
Sometimes, during focusing a small rectangle appears such as in face detection. Could this be related?

**Comment by obs1dium** [comment]
>The app (v1.5) works fine.

That's good to know.

>Sometimes, during focusing a small rectangle appears such as in face detection. Could this be related?

Possibly. I'm only touching three settings at the moment: Scene mode (set to manual), drive mode (set to single shot) and focus mode (set to manual as well).

**Comment by vanderLo** [comment]
Would a log file help?

**Comment by obs1dium** [comment]
I'll add a bit of log output once I find some free time.

**Comment by obs1dium** [comment]
Added some logging (FOCUS.TXT on the SD card), maybe it'll give some insight.
Also fixed the bug you mentioned, please give it a try.
[FocusBracket-release-1.1b.zip](https://github.com/obs1dium/FocusBracket/files/259243/FocusBracket-release-1.1b.zip) (rename to .apk)

**Comment by vanderLo** [comment]
It works now!! Did you change anything else besides adding the code for the log file? 

[FOCUS.TXT](https://github.com/obs1dium/FocusBracket/files/259564/FOCUS.TXT)

**Comment by vanderLo** [comment]
Is the max. picture number predefined/fixed or is it calculated dependent on the distance between the minimum and maximum focus point.

**Comment by obs1dium** [comment]
>Did you change anything else besides adding the code for the log file? 

Yes. I also added a call to disable the cam's self timer (seen in the other bracket app) and disabled ProGuard. Not sure which one made it work for you.

The number of pictures depends on the distance. The total range seems to always consist of 120 steps.

**Comment by vanderLo** [comment]
The 1.1b release works perfectly fine! Couldn't find any bugs. 
Thanks! +1

Nice-to-have-yet-not-important-features:
-Progress indicator
-Menu for ISO settings
-Exposure comp.
-White Balance

**Comment by obs1dium** [comment]
Great. Hopefully the release I just uploaded also works for you.

**Comment by vanderLo** [comment]
Stopped working with the latest 1.1 release

**Comment by obs1dium** [comment]
Ok, then I assume it's either a weird timing issue that was alleviated by the logging or Proguard is causing problems on your cam.

**Comment by obs1dium** [comment]
If you don't mind testing these variants... maybe we can get to the bottom of this.

[FocusBracket-release-1.1_minify_log.zip](https://github.com/obs1dium/FocusBracket/files/261006/FocusBracket-release-1.1_minify_log.zip)
[FocusBracket-release-1.1_no_minify.zip](https://github.com/obs1dium/FocusBracket/files/261007/FocusBracket-release-1.1_no_minify.zip)

**Comment by vanderLo** [comment]
FocusBracket-release-1.1_no_minify: Didn't work
FocusBracket-release-1.1_minify_log: Works. Focus.txt attached.
[FOCUS.TXT](https://github.com/obs1dium/FocusBracket/files/261085/FOCUS.TXT)

**Comment by obs1dium** [comment]
Trying to blindly fix this...
[FocusBracket-release-1.2.zip](https://github.com/obs1dium/FocusBracket/files/261177/FocusBracket-release-1.2.zip)

**Comment by vanderLo** [comment]
I can imagine how difficult it is without having the device..
v1.2 doesn't work.

**Comment by obs1dium** [comment]
Like looking for a black cat in a dark room. One last try:
[FocusBracket-release-1.2.zip](https://github.com/obs1dium/FocusBracket/files/261219/FocusBracket-release-1.2.zip)
If that doesn't work I'll simply re-enable the logging as a workaround until somebody else finds out what's going on.

**Comment by vanderLo** [comment]
Doesn't work either :)

**Comment by obs1dium** [comment]
I tried a 250ms delay right before taking a picture, which apparently didn't help.

**Comment by vanderLo** [comment]
If you wanted to further investigate the delay solution, you could add a focus.cfg file with a param such as "delay: n" (in ms) and "log: n" (0 or 1) I would try different intervals. But I guess writing to a log file is by far the easiest solution. 

Maybe it is also related to delays in between the focus steps..

**Comment by obs1dium** [comment]
I'm out of idea right now. If you or anybody else would like to have a go, please do...
In the meantime I put up a new release with the logging enabled.

**Comment by vanderLo** [comment]
I really don't mind the workaround. Problem solved :+1:
