### ISSUE TITLE
Number of picures to take is not chooseable with a6000

### ISSUE THREAD

**Issue by Crady123** [obs1dium/FocusBracket#18]
Hi there,

I installed your App because I would like to stack more than 3 images.

But Im am not able to increase or decrease the number of pictures using the wheel... I am using a a6000.

Any clues?

Thanks!

**Comment by obs1dium** [comment]
On the a6000 you can change the number of pictures using the control wheel on top of the camera.

**Comment by Crady123** [comment]
Oh... yep that works, thank you!
