### ISSUE TITLE
[a6500] App intermittently stops after taking first shot, waits at "Focusing..." indefinitely

### ISSUE THREAD

**Issue by Ziginox** [obs1dium/FocusBracket#20]
On my a6500 I'm able to properly set min/max focus and choose the number of shots, but the app hangs after the first shot, seemingly unable to change the focus. It's just stuck on "Focusing...", but doesn't seem to have crashed. Occasionally it works, but most of the time it does not. I've attached the log. 
[LOG.TXT](https://github.com/obs1dium/FocusBracket/files/1456414/LOG.TXT)

Additionally, the only way to change the number of shots seems to be the top control dial. Is there a way to use the rear dial and/or dpad?

**Comment by RasmusB** [comment]
I experience the same issue on my A5100 with the kit lens. Any suggestions on a workaround?

**Comment by obs1dium** [comment]
Have a look at the information posted in #9
