### ISSUE TITLE
Takes only one picture on A6000

### ISSUE THREAD

**Issue by cmoetzing** [obs1dium/FocusBracket#3]
Hey, great job on the app.
I already installed firmware 3.1 for my A6000 and switched to manual mode and set ISO, Aperture and Time. Then I open the app and set the focusing distances and choose 3 shots. Unfortunately the app only takes one shot and then stops to do anything. Any ideas? Do I need to use manual focusing mode before opening the app?

**Comment by vanderLo** [comment]
Did you disable Auto review?

**Comment by cmoetzing** [comment]
Will check when I get home.

**Comment by obs1dium** [comment]
The app sets the focusing mode to manual itself, so that's probably not the problem.

**Comment by cmoetzing** [comment]
'Auto review' disabled did the trick. Thank you!

**Comment by obs1dium** [comment]
I found out how to disable auto review in the app, new release is up.
