### ISSUE TITLE
Not working on A7R2

### ISSUE THREAD

**Issue by fotovideoguy** [obs1dium/FocusBracket#32]
I still have not had any luck with gettingthe app to work.
I have installed and uninstalled every version, trying to get it to work.
currently the latest version 1.5 is installed.
When started, I have the minimum and maximum icons on screen and a solid green line between them.
From watching video provided by other users, the app I have installed does not behave as it shows on the A7R2.

I have the lens in AF mode, and set the camera to MF mode, and using Manual mode on the camera as well, but still no luck.

Really would like to know why it works on some A7R2 and not others.

(after trying to reinstall the latest version, I am now not able to install any version of this app.)

Thanks and looking forward to any input that helps to get this working.

**Comment by fotovideoguy** [comment]
Rebooted the computer, reinstalled version 1.5 of the app.
Still not working, same symptoms as above:
When started, I have the minimum and maximum icons on screen and a solid green line between them.
pressing the Centre button does change the dialog on the screen from minimum focus to maximum focus, and...

Thats about it.

**Comment by fotovideoguy** [comment]
How did any of you get this to work? I have had no luck at all getting this to work on my A7R2.
I have tried my adapted Minolta lenses, adapted Canon lenses, and even my Sony emount lens.
What version of the app do you have installed?
I have 1.5 installed and camera firmware 4.00

thank you ,

**Comment by fotovideoguy** [comment]
Finally got it working.
Had to use my Sigma emount 30mm crop sensor lens on the A7R2.
Started the app, manual focus the lens to minimum and maximum points. When doing this i saw the solid green focus bar move.
Got my focusing points in, the number of photos comes up, start the process and you see the progress.
It did not work with my adapted Canon lens unfortunately.
Now to test my Amount lenses when I get home.
It did not seem to matter what focus mode the camera, AF-S to DMF, was in, so if anyone has any input on this, it would be appreciated.

**Comment by fotovideoguy** [comment]
Some testing, and I am only able to get 3 frames from this. 
Demos show a lot more. Is there a setting I am missing in the camera to allow more photos to be made to get better stacked images?

**Comment by fotovideoguy** [comment]
finally found a video that shows the process clearly.
now to test it out in thereal world.
well, with one lens at least. if i can get it to work with the LAE4, then a whole new worl of opportunities.

**Comment by antoineloos** [comment]
@fotovideoguy Hi, are you able to get it to work with your E-mount lenses ? In my side I cannot set the maximum focus point and i'm blocking after that. Can you explain how you solve your issue ? 
Thanks

**Comment by fotovideoguy** [comment]
I am using version 1.5 of the app, the firmware on my A7R2 is v4.00.

Now that I have it installed, I start the app:
I have both close and far icons on the screen and a solid green bar between them.
When I start to manually focus the lens, the green bar between the icons changes, and when I get to the close focus point I want, I press the Centre button. Then I set my far focus point by manually focusing the lens again, then press the Centre button again.
The app is set to take 3 photos, but by using the front dial of the camera where the shutter button is, you can change how many photos the camera will take in order to get a sharper photo.

Hope this helps.

It took me a while to understand the video I was watching, as they assume that you know how the app works,  but there are no instruction on how to make any changes.

Let me know if I can be of more assistance to you with this.

Sam

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
