### ISSUE TITLE
App is now directly installable on sony-pmca.appspot.com

### ISSUE THREAD

**Issue by ma1co** [obs1dium/FocusBracket#5]
I've added your app to the [OpenMemories App List](https://github.com/ma1co/OpenMemories-AppList). It is now directly installable [here](https://sony-pmca.appspot.com/apps).

It automatically fetches the newest apk from your github releases. Please name your tags exactly the same as the version string in your manifest, as you have done in the past.

**Comment by obs1dium** [comment]
Thanks! :)
